# Generated by Django 5.1.1 on 2024-11-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0014_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='vacancy_limit',
            new_name='vacancy_seats',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
