# Generated by Django 5.1.1 on 2024-12-05 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0028_delete_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('current_job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('professional_summary', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('languages_known', models.CharField(blank=True, max_length=200, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Applicant.applicant')),
            ],
        ),
    ]
